language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t odolshinu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true odolshinu/react-test npm test

after_success:
  - docker build -t odolshinu/multi-client ./client
  - docker build -t odolshinu/multi-nginx ./nginx
  - docker build -t odolshinu/multi-server ./server
  - docker build -t odolshinu/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images to docker hub
  - docker push odolshinu/multi-client
  - docker push odolshinu/multi-nginx
  - docker push odolshinu/multi-server
  - docker push odolshinu/multi-worker

deploy:
  provider: elasticbeanstack
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-614395602316
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY