version: "3"
services:
  postgres:
    tty: true
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    tty: true
    image: 'redis:latest'
  api:
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /var/project/node_modules
      - ./server:/var/project
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  client:
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /var/project/node_modules
      - ./client:/var/project
  worker:
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /var/project/node_modules
      - ./worker:/var/project
  nginx:
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - '3050:80'